WITH NETSUITE_DATA AS (
	SELECT 
		a.NAME,	
		a.ACCOUNTNUMBER,
		t.BATCH_NUMBER,
		SUM(tl.AMOUNT_FOREIGN) AS AMOUNT_TOTAL_FOREIGN,
		SUM(tl.AMOUNT) as AMOUNT_TOTAL_USD
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID  
	WHERE 
		tl.ACCOUNT_ID = 2198
	GROUP BY
		a.NAME,	
		a.ACCOUNTNUMBER,
		t.BATCH_NUMBER
	),
	
SETTLEMENTS_DATA AS (
	SELECT
		BATCH_NUMBER,
		CASE 
			WHEN SUM(GROSS) IS NULL THEN 0
			ELSE SUM(GROSS)
		END as SumSettlementGross
	FROM dbfive.dbo.Settlement
	WHERE 
		MERCHANT_ACCOUNT = 'JetBrainsEUR'
	GROUP BY BATCH_NUMBER
)

SELECT
	n.NAME,
	n.ACCOUNTNUMBER,
	n.BATCH_NUMBER,
	AMOUNT_TOTAL_FOREIGN AS NETSUITE_AMOUNT_TOTAL_FOREIGN,
	SumSettlementGross AS SETTLEMENTS_AMOUNT_TOTAL
FROM NETSUITE_DATA n
LEFT JOIN SETTLEMENTS_DATA s ON n.BATCH_NUMBER = s.BATCH_NUMBER
ORDER BY
	BATCH_NUMBER