--FUNGUJICI KOD PRO SETTLEMENTS
SELECT
	ACC_BATCH,
	SumSettlementGross
FROM (
	SELECT
		MERCHANT_ACCOUNT,
		BATCH_NUMBER,
		CONCAT(MERCHANT_ACCOUNT, '_', BATCH_NUMBER) AS ACC_BATCH,
		CASE 
			WHEN SUM(GROSS) IS NULL THEN 0
			ELSE SUM(GROSS)
		END as SumSettlementGross
	FROM dbfive.dbo.Settlement	
	GROUP BY 
		MERCHANT_ACCOUNT,	
		BATCH_NUMBER
	) a
WHERE
	ACC_BATCH IN ('JetBrainsAmericasUSD_', 'JetBrainsAmericasUSD_139', 'JetBrainsAmericasUSD_141', 'JetBrainsEUR_138', 'JetBrainsEUR_139', 'JetBrainsGBP_141')
--

	
--KOD PRO NETSUITE	
select COUNT(ORDER_REF) from dea.netsuite.TRANSACTIONS	
select * from dea.netsuite.TRANSACTION_LINES
select * from dea.netsuite.TRANSACTION_LINES
select * from dea.netsuite.SUBSIDIARIES
select * from dea.netsuite.CURRENCIES
select * from dea.netsuite.ACCOUNTS
select * from dea.netsuite.ENTITY
select COUNT(ORDER_REF) from dbfive.dbo.Settlement

--124768149
SELECT 
--	DISTINCT ORDER_REF,
	SUM(GROSS)
FROM dbfive.dbo.Settlement

SELECT 
--	DISTINCT t.ORDER_REF,
--	s.ORDER_REF,
	SUM(tl.AMOUNT_FOREIGN)
FROM dea.netsuite.TRANSACTIONS t
LEFT JOIN dea.netsuite.TRANSACTION_LINES tl ON tl.TRANSACTION_ID = t.TRANSACTION_ID
LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
JOIN (
	SELECT 
		DISTINCT ORDER_REF,
		GROSS
	FROM dbfive.dbo.Settlement
) s ON t.ORDER_REF = s.ORDER_REF
WHERE a.ACCOUNTNUMBER IN (315700, 315710, 315720, 315800, 548201)
--GROUP BY
--	s.ORDER_REF,
--	t.ORDER_REF
--ORDER BY 
--	t.ORDER_REF


SELECT
	BATCH_COUNTRY,	
	SUM(AMOUNT_TOTAL_FOREIGN) AS AMOUNT_TOTAL_FOREIGN
FROM (
	SELECT
		CONCAT(b.BATCH_NUMBER, '-', b.BILL_COUNTRY) AS BATCH_COUNTRY,
		b.NAME,
		SUM(b.AMOUNT_TOTAL_FOREIGN) AS AMOUNT_TOTAL_FOREIGN
	FROM (
		SELECT 
			a.ACCOUNTNUMBER,
			a.NAME,	
			t.BATCH_NUMBER,
			e.BILL_COUNTRY,
			c.SYMBOL,
			SUM(tl.AMOUNT_FOREIGN) AS AMOUNT_TOTAL_FOREIGN,
			SUM(tl.AMOUNT) as AMOUNT_TOTAL_USD
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		GROUP BY
			a.ACCOUNTNUMBER,
			a.NAME,	
			t.BATCH_NUMBER,
			e.BILL_COUNTRY,
			c.SYMBOL
	) b
	WHERE 
		b.AMOUNT_TOTAL_FOREIGN > 0
		AND b.BILL_COUNTRY = 'GB'
	GROUP BY
		b.NAME,
		b.BATCH_NUMBER,
		b.BILL_COUNTRY
) x
	GROUP BY
		x.BATCH_COUNTRY



		
		

SELECT
	DISTINCT t.BATCH_NUMBER
FROM dea.netsuite.TRANSACTION_LINES tl
LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
--LEFT JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF 
WHERE 
	t.BATCH_NUMBER IS NOT NULL
	AND a.ACCOUNTNUMBER IN (315700, 315710, 315720, 315800, 548201)
ORDER BY 
	t.BATCH_NUMBER

		
		
SELECT TOP (10)
	*
FROM dea.netsuite.TRANSACTIONS t
FULL OUTER JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF
WHERE 
	t.ORDER_REF IS NULL OR s.ORDER_REF IS NULL
		
		
		
	

/*
--
WITH NETSUITE_DATA AS (
	SELECT 
		a.NAME,	
		a.ACCOUNTNUMBER,
		t.BATCH_NUMBER,
		SUM(tl.AMOUNT_FOREIGN) AS AMOUNT_TOTAL_FOREIGN,
		SUM(tl.AMOUNT) as AMOUNT_TOTAL_USD
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID  
	WHERE 
		tl.ACCOUNT_ID = 2198
	GROUP BY
		a.NAME,	
		a.ACCOUNTNUMBER,
		t.BATCH_NUMBER
	),
	
SETTLEMENTS_DATA AS (
	SELECT
		BATCH_NUMBER,
		CASE 
			WHEN SUM(GROSS) IS NULL THEN 0
			ELSE SUM(GROSS)
		END as SumSettlementGross
	FROM dbfive.dbo.Settlement
	WHERE 
		MERCHANT_ACCOUNT = 'JetBrainsEUR'
	GROUP BY BATCH_NUMBER
)

SELECT
	n.NAME,
	n.ACCOUNTNUMBER,
	n.BATCH_NUMBER,
	AMOUNT_TOTAL_FOREIGN AS NETSUITE_AMOUNT_TOTAL_FOREIGN,
	SumSettlementGross AS SETTLEMENTS_AMOUNT_TOTAL
FROM NETSUITE_DATA n
LEFT JOIN SETTLEMENTS_DATA s ON n.BATCH_NUMBER = s.BATCH_NUMBER
ORDER BY
	BATCH_NUMBER
--
*/

--	

--SELECT 
--	SUM(NETSUITE_AMOUNT_TOTAL_USD) AS NETSUITE_AMOUNT_TOTAL_USD,
--	SUM(NETSUITE_AMOUNT_TOTAL_CUR) AS NETSUITE_AMOUNT_TOTAL_CUR
--FROM (
--	SELECT 
--		t.TRANSACTION_ID, 
--		t.ORDER_REF,
--		t.TRANDATE,
--		t.DATE_LAST_MODIFIED,
--		t.TRANSACTION_TYPE,
--		t.BATCH_NUMBER,
--		sub.COUNTRY,
--		SUM(tl.AMOUNT) AS NETSUITE_AMOUNT_TOTAL_USD,
--		SUM(tl.AMOUNT_FOREIGN) AS NETSUITE_AMOUNT_TOTAL_CUR
--	FROM dea.netsuite.TRANSACTIONS t
--	LEFT JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF
--	LEFT JOIN dea.netsuite.TRANSACTION_LINES tl ON tl.TRANSACTION_ID = t.TRANSACTION_ID
--	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
--	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID 
--	WHERE
----		a.ACCOUNTNUMBER = 315700
----		AND t.BATCH_NUMBER = 140
--		sub.COUNTRY = 'US'
--	GROUP BY
--		t.TRANSACTION_ID, 
--		t.ORDER_REF,
--		t.TRANDATE,
--		t.DATE_LAST_MODIFIED,
--		t.TRANSACTION_TYPE,
--		t.BATCH_NUMBER,
--		sub.COUNTRY
--	) a
	