/* SEARCHING FOR DIFFERENT ORDERS BETWEEN NETSUITE AND SETTLEMENTS */
/* DETAIL NS*/
WITH netsuite as (
	SELECT
		DISTINCT ORDER_REF
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	WHERE 
		 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
		 AND a.ACCOUNTNUMBER IN (315700, 548201)
		 AND c.SYMBOL = 'EUR'
		 AND t.BATCH_NUMBER = 142
),	 
/* DETAIL SETTLEMENTS*/
settlements as (
	SELECT
		DISTINCT ORDER_REF
	FROM dbfive.dbo.Settlement
	WHERE 
		MERCHANT_ACCOUNT = 'JetBrainsEUR'
		AND BATCH_NUMBER = 142
)
/* JOIN NETSUITE AND SETTLEMENTS ORDERS TO FIND NOT MATCHING ORDERS */
SELECT
	n.ORDER_REF as NetsuiteOrderRef,
	s.ORDER_REF as SettlementsOrderRef
FROM netsuite n
LEFT JOIN settlements s ON s.ORDER_REF = n.ORDER_REF
WHERE s.ORDER_REF IS NULL