/* AGGREGATED QUERIES WITH CORRECT FILTERS  */

/* GBP */
SELECT
	SUM(AMOUNT_FOREIGN)
FROM dea.netsuite.TRANSACTION_LINES tl
LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
WHERE 
	 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
	 AND a.ACCOUNTNUMBER IN (315720, 548201)
	 AND c.SYMBOL = 'GBP'
	 AND t.BATCH_NUMBER = 142
	 AND e.BILL_COUNTRY IN ('GB')



/* EUR */
SELECT
	SUM(AMOUNT_FOREIGN)
FROM dea.netsuite.TRANSACTION_LINES tl
LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
WHERE 
	 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
	 AND a.ACCOUNTNUMBER IN (315700, 548201)
	 AND c.SYMBOL = 'EUR'
	 AND t.BATCH_NUMBER = 138
	 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')



/* USD AMERICAS*/
SELECT
	SUM(AMOUNT_FOREIGN)
FROM dea.netsuite.TRANSACTION_LINES tl
LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
WHERE
	t.MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
	AND sub.TRAN_NUM_PREFIX = 'JBA'
	AND a.ACCOUNTNUMBER IN (315710, 548201)
	AND c.SYMBOL = 'USD'
--	AND t.BATCH_NUMBER IS NULL		-- PRO BATCH_NUMBER IS NULL
--	AND t.BATCH_NUMBER IN (138, 140, 142)	-- PRO BATCH_NUMBER <> NULL
