/* Creating a list of all differences between NetSuite and payment gateway */

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS NULL
WITH americasUSDnull AS (
	SELECT
		DISTINCT t.ORDER_REF
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	LEFT JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF
	WHERE
		t.MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND sub.TRAN_NUM_PREFIX = 'JBA'
		AND a.ACCOUNTNUMBER IN (315710, 548201)
		AND c.SYMBOL = 'USD'
		AND t.BATCH_NUMBER IS NULL
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS 139
americasUSD139 AS (
	SELECT
		DISTINCT t.ORDER_REF
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	LEFT JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF
	WHERE
		t.MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND sub.TRAN_NUM_PREFIX = 'JBA'
		AND a.ACCOUNTNUMBER IN (315710, 548201)
		AND c.SYMBOL = 'USD'
		AND s.BATCH_NUMBER = 139
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS 139
americasUSD141 AS (
	SELECT
		DISTINCT t.ORDER_REF
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	LEFT JOIN dbfive.dbo.Settlement s ON t.ORDER_REF = s.ORDER_REF
	WHERE
		t.MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND sub.TRAN_NUM_PREFIX = 'JBA'
		AND a.ACCOUNTNUMBER IN (315710, 548201)
		AND c.SYMBOL = 'USD'
		AND s.BATCH_NUMBER = 141
),

/*
 * Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 138
 * Netsuite and Settlements have same ORDER_REFs but prices (GROSS, AMOUNT_FOREIGN) are different in some orders
*/
EUR138 AS (
	SELECT
		 NS_ORDER_REF AS ORDER_REF
	FROM (
		SELECT
			DISTINCT t.ORDER_REF AS NS_ORDER_REF,
			t.BATCH_NUMBER,
			SUM(AMOUNT_FOREIGN) AS AMOUNT_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		WHERE -- Netsuite data filtration
			 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
			 AND a.ACCOUNTNUMBER IN (315700, 548201)
			 AND c.SYMBOL = 'EUR'
			 AND t.BATCH_NUMBER = 138
			 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
		GROUP BY 
			ORDER_REF,
			t.BATCH_NUMBER
	) ns
	LEFT JOIN ( -- Joining settlement data
		SELECT 
			DISTINCT ORDER_REF AS SETT_ORDER_REF,
			BATCH_NUMBER,
			SUM(GROSS) AS GROSS
		FROM dbfive.dbo.Settlement
		WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'	-- Settlement data filtration
			AND BATCH_NUMBER = 138
		GROUP BY 
			ORDER_REF,
			BATCH_NUMBER
	) s ON ns.NS_ORDER_REF = s.SETT_ORDER_REF
	WHERE AMOUNT_FOREIGN <> GROSS	-- Returns only those orders, where price is different	
	),

/* Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139 
 * Query is separated to two parts because in this account and batch there are some missing orders and unmatching prices as well
 *
 * Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139
 * Netsuite and Settlements have same ORDER_REFs but prices (GROSS, AMOUNT_FOREIGN) are different in some orders
*/
PricesEUR139 AS (
	SELECT
		NS_ORDER_REF AS ORDER_REF
	FROM (
		SELECT
			DISTINCT t.ORDER_REF AS NS_ORDER_REF,
			t.BATCH_NUMBER,
			SUM(AMOUNT_FOREIGN) AS AMOUNT_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		WHERE 
			 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
			 AND a.ACCOUNTNUMBER IN (315700, 548201)
			 AND c.SYMBOL = 'EUR'
			 AND t.BATCH_NUMBER = 139
			 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
		GROUP BY 
			ORDER_REF,
			t.BATCH_NUMBER
	) ns
	LEFT JOIN (
		SELECT 
			DISTINCT ORDER_REF AS SETT_ORDER_REF,
			BATCH_NUMBER,
			SUM(GROSS) AS GROSS
		FROM dbfive.dbo.Settlement
		WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'
			AND BATCH_NUMBER = 139
		GROUP BY 
			ORDER_REF,
			BATCH_NUMBER
	) s ON ns.NS_ORDER_REF = s.SETT_ORDER_REF
	WHERE AMOUNT_FOREIGN <> GROSS
),

/* Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139 */
-- Getting missing orders
MissingEUR139 AS (
	SELECT 
		SETT_ORDER_REF AS ORDER_REF
	FROM (
		SELECT
		DISTINCT t.ORDER_REF AS NS_ORDER_REF,
		t.BATCH_NUMBER,
		SUM(AMOUNT_FOREIGN) AS AMOUNT_FOREIGN
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	WHERE 
		 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
		 AND a.ACCOUNTNUMBER IN (315700, 548201)
		 AND c.SYMBOL = 'EUR'
		 AND t.BATCH_NUMBER = 139
		 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
	GROUP BY 
		ORDER_REF,
		t.BATCH_NUMBER
	) ns
	RIGHT JOIN (
		SELECT 
		DISTINCT ORDER_REF AS SETT_ORDER_REF,
		BATCH_NUMBER,
		SUM(GROSS) AS GROSS
	FROM dbfive.dbo.Settlement
	WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'
		AND BATCH_NUMBER = 139
	GROUP BY 
		ORDER_REF,
		BATCH_NUMBER
	) s 
		ON s.SETT_ORDER_REF = ns.NS_ORDER_REF
	WHERE
		ns.NS_ORDER_REF IS NULL
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasGBP' AND BATCH_NUMBER IS 141
GBP141 AS (
	SELECT 
		SETT_ORDER_REF AS ORDER_REF
	FROM (
		SELECT 
			DISTINCT ORDER_REF AS SETT_ORDER_REF,
			BATCH_NUMBER,
			SUM(GROSS) AS GROSS
		FROM dbfive.dbo.Settlement
		WHERE 
			MERCHANT_ACCOUNT = 'JetBrainsGBP'
			AND BATCH_NUMBER = 141
		GROUP BY 
			ORDER_REF,
			BATCH_NUMBER
	) s
		LEFT JOIN (
		SELECT
			DISTINCT t.ORDER_REF as NS_ORDER_REF,
			t.BATCH_NUMBER,
			SUM(AMOUNT_FOREIGN) as AMOUNT_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		WHERE 
			 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
	 		AND a.ACCOUNTNUMBER IN (315720, 548201)
	 		AND c.SYMBOL = 'GBP'
	 		AND t.BATCH_NUMBER = 141
	 		AND e.BILL_COUNTRY IN ('GB')
		GROUP BY 
			ORDER_REF,
			t.BATCH_NUMBER
	) ns
	ON s.SETT_ORDER_REF = ns.NS_ORDER_REF
)

-- Saving the result into table for further data enrichment
SELECT * INTO dbfive.dbo.ns_sett_diff FROM(
-- Merging all subqueries to get list of unmatched ORDER_REFs 
	SELECT * FROM americasUSDnull
	UNION ALL
	SELECT * FROM americasUSD139
	UNION ALL
	SELECT * FROM americasUSD141
	UNION ALL
	SELECT * FROM EUR138
	UNION ALL
	SELECT * FROM PricesEUR139
	UNION ALL
	SELECT * FROM MissingEUR139
	UNION ALL
	SELECT * FROM GBP141
) un