/* Creating a list of all differences between NetSuite and payment gateway */

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS NULL
WITH americasUSDnull AS (
	SELECT
		DISTINCT t.TRANSACTION_ID,
		t.ORDER_REF,
		t.TRANDATE,
		t.TRANSACTION_TYPE,
		t.BATCH_NUMBER,
		sub.TRAN_NUM_PREFIX,
		sub.NAME AS SUBSIDIARY_NAME,
		a.ACCOUNTNUMBER,
		IS_NON_POSTING,
		a.FULL_NAME,
		a.ISINACTIVE,
		a.IS_BALANCESHEET,
		a.IS_LEFTSIDE,
		a.IS_SUMMARY,
		a.TYPE_NAME,
		a.TYPE_SEQUENCE,
		e.ENTITY_ID,
		e.NAME,
		e.ENTITY_TYPE,
		e.BILL_COUNTRY,
		c.SYMBOL,
		tl.AMOUNT AS NETSUITE_PRICE,
		tl.AMOUNT_FOREIGN AS NETSUITE_PRICE_FOREIGN,
		NULL AS MERCHANT_ACCOUNT,
		NULL AS SETTLEMENT_BATCH_NUMBER,
		NULL AS SETTLEMENT_PAYMENT_METHOD,
		NULL AS SETTLEMENT_TYPE,
		NULL AS SETTLEMENT_NET,
		NULL AS SETTLEMENT_FEE,
		NULL AS SETTLEMENT_GROSS,
		'in_netsuite' AS FLAG
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	WHERE
		t.MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
		AND sub.TRAN_NUM_PREFIX = 'JBA'
		AND a.ACCOUNTNUMBER IN (315710, 548201)
		AND c.SYMBOL = 'USD'
		AND t.BATCH_NUMBER IS NULL
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS 139
americasUSD139 AS (
	SELECT
		NULL AS TRANSACTION_ID,
		NULL AS ORDER_REF,
		NULL AS TRANDATE,
		NULL AS TRANSACTION_TYPE,
		NULL AS BATCH_NUMBER,
		NULL AS TRAN_NUM_PREFIX,
		NULL AS SUBSIDIARY_NAME,
		NULL AS ACCOUNTNUMBER,
		NULL AS IS_NON_POSTING,
		NULL AS FULL_NAME,
		NULL AS ISINACTIVE,
		NULL AS IS_BALANCESHEET,
		NULL AS IS_LEFTSIDE,
		NULL AS IS_SUMMARY,
		NULL AS TYPE_NAME,
		NULL AS TYPE_SEQUENCE,
		NULL AS ENTITY_ID,
		NULL AS NAME,
		NULL AS ENTITY_TYPE,
		NULL AS BILL_COUNTRY,
		NULL AS SYMBOL,
		NULL AS NETSUITE_PRICE,
		NULL AS NETSUITE_PRICE_FOREIGN,
		MERCHANT_ACCOUNT,
		BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
		PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
		TYPE AS SETTLEMENT_TYPE,
		NET AS SETTLEMENT_NET,
		FEE AS SETTLEMENT_FEE,
		GROSS AS SETTLEMENT_GROSS,
		'in_settlements' AS FLAG
	FROM dbfive.dbo.Settlement s
	WHERE
		MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND BATCH_NUMBER = 139
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD' AND BATCH_NUMBER IS 139
americasUSD141 AS (
	SELECT
		NULL AS TRANSACTION_ID,
		NULL AS ORDER_REF,
		NULL AS TRANDATE,
		NULL AS TRANSACTION_TYPE,
		NULL AS BATCH_NUMBER,
		NULL AS TRAN_NUM_PREFIX,
		NULL AS SUBSIDIARY_NAME,
		NULL AS ACCOUNTNUMBER,
		NULL AS IS_NON_POSTING,
		NULL AS FULL_NAME,
		NULL AS ISINACTIVE,
		NULL AS IS_BALANCESHEET,
		NULL AS IS_LEFTSIDE,
		NULL AS IS_SUMMARY,
		NULL AS TYPE_NAME,
		NULL AS TYPE_SEQUENCE,
		NULL AS ENTITY_ID,
		NULL AS NAME,
		NULL AS ENTITY_TYPE,
		NULL AS BILL_COUNTRY,
		NULL AS SYMBOL,
		NULL AS NETSUITE_PRICE,
		NULL AS NETSUITE_PRICE_FOREIGN,
		MERCHANT_ACCOUNT,
		BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
		PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
		TYPE AS SETTLEMENT_TYPE,
		NET AS SETTLEMENT_NET,
		FEE AS SETTLEMENT_FEE,
		GROSS AS SETTLEMENT_GROSS,
		'in_settlements' AS FLAG
	FROM dbfive.dbo.Settlement s
	WHERE
		MERCHANT_ACCOUNT = 'JetBrainsAmericasUSD'
		AND s.BATCH_NUMBER = 141
),

/*
 * Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 138
 * Netsuite and Settlements have same ORDER_REFs but prices (GROSS, AMOUNT_FOREIGN) are different in some orders
*/
EUR138 AS (
	SELECT
		DISTINCT ns.TRANSACTION_ID,
		ns.ORDER_REF,
		ns.TRANDATE,
		ns.TRANSACTION_TYPE,
		ns.BATCH_NUMBER,
		ns.TRAN_NUM_PREFIX,
		ns.NAME AS SUBSIDIARY_NAME,
		ns.ACCOUNTNUMBER,
		ns.IS_NON_POSTING,
		ns.FULL_NAME,
		ns.ISINACTIVE,
		ns.IS_BALANCESHEET,
		ns.IS_LEFTSIDE,
		ns.IS_SUMMARY,
		ns.TYPE_NAME,
		ns.TYPE_SEQUENCE,
		ns.ENTITY_ID,
		ns.NAME,
		ns.ENTITY_TYPE,
		ns.BILL_COUNTRY,
		ns.SYMBOL,
		ns.NETSUITE_PRICE,
		ns.NETSUITE_PRICE_FOREIGN,
		s.MERCHANT_ACCOUNT,
		s.SETTLEMENT_BATCH_NUMBER,
		s.SETTLEMENT_PAYMENT_METHOD,
		s.SETTLEMENT_TYPE,
		s.SETTLEMENT_NET,
		s.SETTLEMENT_FEE,
		s.SETTLEMENT_GROSS,
		'different_prices' AS FLAG
	FROM (
		SELECT
			t.TRANSACTION_ID,
			t.ORDER_REF,
			t.TRANDATE,
			t.TRANSACTION_TYPE,
			t.BATCH_NUMBER,
			sub.TRAN_NUM_PREFIX,
			sub.NAME AS SUBSIDIARY_NAME,
			a.ACCOUNTNUMBER,
			IS_NON_POSTING,
			a.FULL_NAME,
			a.ISINACTIVE,
			a.IS_BALANCESHEET,
			a.IS_LEFTSIDE,
			a.IS_SUMMARY,
			a.TYPE_NAME,
			a.TYPE_SEQUENCE,
			e.ENTITY_ID,
			e.NAME,
			e.ENTITY_TYPE,
			e.BILL_COUNTRY,
			c.SYMBOL,
			tl.AMOUNT AS NETSUITE_PRICE,
			tl.AMOUNT_FOREIGN AS NETSUITE_PRICE_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		WHERE -- Netsuite data filtration
			 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
			 AND a.ACCOUNTNUMBER IN (315700, 548201)
			 AND c.SYMBOL = 'EUR'
			 AND t.BATCH_NUMBER = 138
			 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
	) ns
	LEFT JOIN ( -- Joining settlement data
		SELECT 
			ORDER_REF,
			BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
			PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
			MERCHANT_ACCOUNT,
			TYPE AS SETTLEMENT_TYPE,
			NET AS SETTLEMENT_NET,
			FEE AS SETTLEMENT_FEE,
			GROSS AS SETTLEMENT_GROSS
		FROM dbfive.dbo.Settlement
		WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'	-- Settlement data filtration
			AND BATCH_NUMBER = 138
	) s ON ns.ORDER_REF = s.ORDER_REF
	WHERE ns.NETSUITE_PRICE_FOREIGN <> s.SETTLEMENT_GROSS	-- Returns only those orders, where price is different	
	),

/* Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139 
 * Query is separated to two parts because in this account and batch there are some missing orders and unmatching prices as well
 *
 * Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139
 * Netsuite and Settlements have same ORDER_REFs but prices (GROSS, AMOUNT_FOREIGN) are different in some orders
*/
PricesEUR139 AS (
	SELECT
		DISTINCT ns.TRANSACTION_ID,
		ns.ORDER_REF,
		ns.TRANDATE,
		ns.TRANSACTION_TYPE,
		ns.BATCH_NUMBER,
		ns.TRAN_NUM_PREFIX,
		ns.NAME AS SUBSIDIARY_NAME,
		ns.ACCOUNTNUMBER,
		ns.IS_NON_POSTING,
		ns.FULL_NAME,
		ns.ISINACTIVE,
		ns.IS_BALANCESHEET,
		ns.IS_LEFTSIDE,
		ns.IS_SUMMARY,
		ns.TYPE_NAME,
		ns.TYPE_SEQUENCE,
		ns.ENTITY_ID,
		ns.NAME,
		ns.ENTITY_TYPE,
		ns.BILL_COUNTRY,
		ns.SYMBOL,
		ns.NETSUITE_PRICE,
		ns.NETSUITE_PRICE_FOREIGN,
		s.MERCHANT_ACCOUNT,
		s.SETTLEMENT_BATCH_NUMBER,
		s.SETTLEMENT_PAYMENT_METHOD,
		s.SETTLEMENT_TYPE,
		s.SETTLEMENT_NET,
		s.SETTLEMENT_FEE,
		s.SETTLEMENT_GROSS,
		'different_prices' AS FLAG
	FROM (
		SELECT
			t.TRANSACTION_ID,
			t.ORDER_REF,
			t.TRANDATE,
			t.TRANSACTION_TYPE,
			t.BATCH_NUMBER,
			sub.TRAN_NUM_PREFIX,
			sub.NAME AS SUBSIDIARY_NAME,
			a.ACCOUNTNUMBER,
			IS_NON_POSTING,
			a.FULL_NAME,
			a.ISINACTIVE,
			a.IS_BALANCESHEET,
			a.IS_LEFTSIDE,
			a.IS_SUMMARY,
			a.TYPE_NAME,
			a.TYPE_SEQUENCE,
			e.ENTITY_ID,
			e.NAME,
			e.ENTITY_TYPE,
			e.BILL_COUNTRY,
			c.SYMBOL,
			tl.AMOUNT AS NETSUITE_PRICE,
			tl.AMOUNT_FOREIGN AS NETSUITE_PRICE_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		WHERE 
			 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
			 AND a.ACCOUNTNUMBER IN (315700, 548201)
			 AND c.SYMBOL = 'EUR'
			 AND t.BATCH_NUMBER = 139
			 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
	) ns
	LEFT JOIN (
		SELECT 
			ORDER_REF,
			BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
			PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
			MERCHANT_ACCOUNT,
			TYPE AS SETTLEMENT_TYPE,
			NET AS SETTLEMENT_NET,
			FEE AS SETTLEMENT_FEE,
			GROSS AS SETTLEMENT_GROSS
		FROM dbfive.dbo.Settlement
		WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'
			AND BATCH_NUMBER = 139
	) s ON ns.ORDER_REF = s.ORDER_REF
	WHERE NETSUITE_PRICE_FOREIGN <> SETTLEMENT_GROSS
),

/* Query for MERCHANT_ACCOUNT = 'JetBrainsEUR' AND BATCH_NUMBER IS 139 */
-- Getting missing orders
MissingEUR139 AS (
	SELECT 
		DISTINCT ns.TRANSACTION_ID,
		ns.ORDER_REF,
		ns.TRANDATE,
		ns.TRANSACTION_TYPE,
		ns.BATCH_NUMBER,
		ns.TRAN_NUM_PREFIX,
		ns.NAME AS SUBSIDIARY_NAME,
		ns.ACCOUNTNUMBER,
		ns.IS_NON_POSTING,
		ns.FULL_NAME,
		ns.ISINACTIVE,
		ns.IS_BALANCESHEET,
		ns.IS_LEFTSIDE,
		ns.IS_SUMMARY,
		ns.TYPE_NAME,
		ns.TYPE_SEQUENCE,
		ns.ENTITY_ID,
		ns.NAME,
		ns.ENTITY_TYPE,
		ns.BILL_COUNTRY,
		ns.SYMBOL,
		ns.NETSUITE_PRICE,
		ns.NETSUITE_PRICE_FOREIGN,
		s.MERCHANT_ACCOUNT,
		s.SETTLEMENT_BATCH_NUMBER,
		s.SETTLEMENT_PAYMENT_METHOD,
		s.SETTLEMENT_TYPE,
		s.SETTLEMENT_NET,
		s.SETTLEMENT_FEE,
		s.SETTLEMENT_GROSS,
		'in_settlements' AS FLAG
	FROM (
		SELECT
		t.TRANSACTION_ID,
		t.ORDER_REF,
		t.TRANDATE,
		t.TRANSACTION_TYPE,
		t.BATCH_NUMBER,
		sub.TRAN_NUM_PREFIX,
		sub.NAME AS SUBSIDIARY_NAME,
		a.ACCOUNTNUMBER,
		IS_NON_POSTING,
		a.FULL_NAME,
		a.ISINACTIVE,
		a.IS_BALANCESHEET,
		a.IS_LEFTSIDE,
		a.IS_SUMMARY,
		a.TYPE_NAME,
		a.TYPE_SEQUENCE,
		e.ENTITY_ID,
		e.NAME,
		e.ENTITY_TYPE,
		e.BILL_COUNTRY,
		c.SYMBOL,
		tl.AMOUNT AS NETSUITE_PRICE,
		tl.AMOUNT_FOREIGN AS NETSUITE_PRICE_FOREIGN
	FROM dea.netsuite.TRANSACTION_LINES tl
	LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
	LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
	LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
	LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
	LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
	WHERE 
		 t.TRANSACTION_TYPE IN ('Payment', 'Customer Deposit')
		 AND a.ACCOUNTNUMBER IN (315700, 548201)
		 AND c.SYMBOL = 'EUR'
		 AND t.BATCH_NUMBER = 139
		 AND e.BILL_COUNTRY IN ('AT','DE', 'CH')
	) ns
	RIGHT JOIN (
		SELECT 
		ORDER_REF,
		BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
		PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
		MERCHANT_ACCOUNT,
		TYPE AS SETTLEMENT_TYPE,
		NET AS SETTLEMENT_NET,
		FEE AS SETTLEMENT_FEE,
		GROSS AS SETTLEMENT_GROSS
	FROM dbfive.dbo.Settlement
	WHERE MERCHANT_ACCOUNT = 'JetBrainsEUR'
		AND BATCH_NUMBER = 139
	) s 
		ON s.ORDER_REF = ns.ORDER_REF
	WHERE
		ns.ORDER_REF IS NULL
),

-- Query for MERCHANT_ACCOUNT = 'JetBrainsAmericasGBP' AND BATCH_NUMBER IS 141
GBP141 AS (
	SELECT
		NULL AS TRANSACTION_ID,
		NULL AS ORDER_REF,
		NULL AS TRANDATE,
		NULL AS TRANSACTION_TYPE,
		NULL AS BATCH_NUMBER,
		NULL AS TRAN_NUM_PREFIX,
		NULL AS SUBSIDIARY_NAME,
		NULL AS ACCOUNTNUMBER,
		NULL AS IS_NON_POSTING,
		NULL AS FULL_NAME,
		NULL AS ISINACTIVE,
		NULL AS IS_BALANCESHEET,
		NULL AS IS_LEFTSIDE,
		NULL AS IS_SUMMARY,
		NULL AS TYPE_NAME,
		NULL AS TYPE_SEQUENCE,
		NULL AS ENTITY_ID,
		NULL AS NAME,
		NULL AS ENTITY_TYPE,
		NULL AS BILL_COUNTRY,
		NULL AS SYMBOL,
		NULL AS NETSUITE_PRICE,
		NULL AS NETSUITE_PRICE_FOREIGN,
		MERCHANT_ACCOUNT,
		BATCH_NUMBER AS SETTLEMENT_BATCH_NUMBER,
		PAYMENT_METHOD AS SETTLEMENT_PAYMENT_METHOD,
		TYPE AS SETTLEMENT_TYPE,
		NET AS SETTLEMENT_NET,
		FEE AS SETTLEMENT_FEE,
		GROSS AS SETTLEMENT_GROSS,
		'in_settlements' AS FLAG
	FROM dbfive.dbo.Settlement s
	WHERE
		MERCHANT_ACCOUNT = 'JetBrainsGBP'
		AND s.BATCH_NUMBER = 141
)

-- Saving the result into table for further data enrichment
SELECT * INTO dbfive.dbo.netsuite_settlement_differences FROM(
-- Merging all subqueries to get the list of all differences 
	SELECT * FROM americasUSDnull
	UNION ALL
	SELECT * FROM americasUSD139
	UNION ALL
	SELECT * FROM americasUSD141
	UNION ALL
	SELECT * FROM EUR138
	UNION ALL
	SELECT * FROM PricesEUR139
	UNION ALL
	SELECT * FROM MissingEUR139
	UNION ALL
	SELECT * FROM GBP141
) nsd