/* Task1 Netsuite investigation */
SELECT
	x.ACCOUNTNUMBER,
	x.NAME,
	x.BATCH_NUMBER,
	x.SYMBOL,
	SUM(AMOUNT_TOTAL_FOREIGN) AS AMOUNT_TOTAL_FOREIGN
FROM (
	SELECT
		b.ACCOUNTNUMBER,
		b.NAME,
		b.BATCH_NUMBER,
		b.SYMBOL,
		SUM(b.AMOUNT_TOTAL_FOREIGN) AS AMOUNT_TOTAL_FOREIGN
	FROM (
		SELECT 
			a.ACCOUNTNUMBER,
			a.NAME,	
			t.BATCH_NUMBER,
			e.BILL_COUNTRY,
			c.SYMBOL,
			SUM(tl.AMOUNT_FOREIGN) AS AMOUNT_TOTAL_FOREIGN
		FROM dea.netsuite.TRANSACTION_LINES tl
		LEFT JOIN dea.netsuite.SUBSIDIARIES sub ON tl.SUBSIDIARY_ID = sub.SUBSIDIARY_ID
		LEFT JOIN dea.netsuite.ACCOUNTS a ON tl.ACCOUNT_ID = a.ACCOUNT_ID
		LEFT JOIN dea.netsuite.TRANSACTIONS t ON tl.TRANSACTION_ID = t.TRANSACTION_ID
		LEFT JOIN dea.netsuite.ENTITY e ON tl.COMPANY_ID = e.ENTITY_ID
		LEFT JOIN dea.netsuite.CURRENCIES c ON t.CURRENCY_ID = c.CURRENCY_ID
		GROUP BY
			a.ACCOUNTNUMBER,
			a.NAME,	
			t.BATCH_NUMBER,
			e.BILL_COUNTRY,
			c.SYMBOL
	) b
	WHERE 
		b.AMOUNT_TOTAL_FOREIGN > 0
		AND b.SYMBOL IN ('GBP', 'EUR')
	GROUP BY
		b.ACCOUNTNUMBER,
		b.NAME,	
		b.BATCH_NUMBER,
		b.SYMBOL
) x
	GROUP BY
		x.ACCOUNTNUMBER,
		x.NAME,
		x.BATCH_NUMBER,
		x.SYMBOL